name: Create Release

on:
  push:
    branches:
      - main

jobs:
  create-release:
    uses: liquibase/build-logic/.github/workflows/create-release.yml@fix-release-prepare-rollback
    secrets: inherit
